### ISSUE TITLE
Add another fast bowler to the team.

### ISSUE THREAD

**Issue by rickgrimes1948** [AshenJayasuriya/NeverGiveUp#6]
Go through the team list and add another fast bowler at the end.

**Comment by AshenJayasuriya** [comment]
Please add Nuwan Kulasekara at the end.

**Comment by rickgrimes1948** [comment]
> Please add Nuwan Kulasekara at the end.

Dilhara Fernando would be a better choise.

**Comment by rickgrimes1948** [comment]
> Please add Nuwan Kulasekara at the end.

ha haa

**Comment by AshenJayasuriya** [comment]
he heee

**Comment by rickgrimes1948** [comment]
Issu fixed.

**Comment by AshenJayasuriya** [comment]
IT is good to add Suranga Lakmal too.

**Comment by AshenJayasuriya** [comment]
This is Fixed.
