### ISSUE TITLE
Yes If should added as Avocado fruit in the list.

### ISSUE THREAD

**Issue by AshenJayasuriya** [AshenJayasuriya/NeverGiveUp#7]
Yes If should added as **Avocado** fruit in the list.

_Originally posted by @rickgrimes1948 in https://github.com/AshenJayasuriya/NeverGiveUp/issues/3#issuecomment-636177395_

**Comment by rickgrimes1948** [comment]
I think its already added.

**Comment by AshenJayasuriya** [comment]
Thanks.
